name: flutter_wanandroid
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
   # 本地语言包
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  event_bus: ^1.0.1
  fluro: ^1.3.4
  # image_picker: ^0.4.10
  sqflite: ^0.12.1
  flutter_markdown: ^0.2.0
  url_launcher: ^4.0.1
  # 本地存储、收藏功能
  shared_preferences: ^0.4.3
  # 网络请求库
  dio: ^3.0.9
  # cookie 管理
  cookie_jar: ^1.0.1
  dio_cookie_manager: 1.0.0
  flutter_webview_plugin: ^0.3.0+2
  # 日期格式化
  #  intl: 0.15.7
  # city_pickers: ^0.1.0
  # 下拉刷新库
  flutter_easyrefresh: ^2.0.9
  # 图片库
  extended_image: ^0.7.1
  # Toast
  fluttertoast: ^3.1.3
  # 屏幕适配
  flutter_screenutil: ^1.0.2
  # 瀑布流
  flutter_staggered_grid_view: ^0.3.0
  # 显示 html
  flutter_html: ^0.11.1
  # google 图标
  groovin_material_icons: ^1.1.5
  # 获取临时目录和文档目录
  path_provider: ^1.6.5
  # provider 依赖注入和状态管理
  provider: ^4.0.5
#  # 相机
#  camera: ^0.5.8+1
#  # 视频
#  video_player: ^0.10.11
  # 极光推送
  jpush_flutter:
    git:
      url: git://github.com/jpush/jpush-flutter-plugin.git
      ref: master
  # bugly
  flutter_bugly:
    git:
      url: git://github.com/crazecoder/flutter_bugly.git
      ref: dev

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/app.db
    - assets/images/
    - assets/fonts/


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
